// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

// Tratamento caso DATABASE_URL não tenha sido definida
const DATABASE_URL = process.env["DATABASE_URL"]
if (!DATABASE_URL){
  throw new Error("Erro: DATABASE_URL não foi encontrada no arquivo .env")
}

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "./prisma/seed.ts"
  },
  datasource: {
    url: DATABASE_URL,
  },
});
